### Checking Data and It's Quality

In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 

df = pd.read_csv('export.csv') 

df.head()

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 GEOID
0,1N4AZ1CP3K,King,Shoreline,WA,98155.0,2019,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,150.0,32.0,168526641,POINT (-122.30304 47.75494),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303302e+10
1,WBY8P4C51K,King,Kirkland,WA,98033.0,2019,BMW,I3,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,126.0,48.0,9418181,POINT (-122.2066 47.67887),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303302e+10
2,3FA6P0SU8G,Snohomish,Lynnwood,WA,98036.0,2016,FORD,FUSION,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,19.0,1.0,172853495,POINT (-122.29245 47.82557),PUGET SOUND ENERGY INC,5.306105e+10
3,5YJ3E1EB3N,Yakima,Wapato,WA,98951.0,2022,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,15.0,204768175,POINT (-120.42083 46.44779),PACIFICORP,5.307794e+10
4,WBY1Z2C53F,King,Renton,WA,98055.0,2015,BMW,I3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,81.0,11.0,269262920,POINT (-122.19488 47.44034),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10

In [3]:
df.info() 


df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299705 entries, 0 to 299704
Data columns (total 16 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   VIN (1-10)                                         299705 non-null  object
 1   County                                             299694 non-null  object
 2   City                                               299694 non-null  object
 3   State                                              299705 non-null  object
 4   Postal Code                                        299694 non-null  float64
 5   Model Year                                         299705 non-null  int64
 6   Make                                               299705 non-null  object
 7   Model                                              299705 non-null  object
 8   Electric Vehicle Type                              299705 non-null  object
 9   Clean Alternative Fuel Vehicle (CAFV) Eligibility  299705 non-null  object
 10  Electric Range                                     299679 non-null  float64
 11  Legislative District                               298915 non-null  float64
 12  DOL Vehicle ID                                     299705 non-null  int64
 13  Vehicle Location                                   299685 non-null  object
 14  Electric Utility                                   299694 non-null  object
 15  2020 GEOID                                         299694 non-null  float64
dtypes: float64(4), int64(2), object(10)
memory usage: 36.6+ MB

,Postal Code,Model Year,Electric Range,Legislative District,DOL Vehicle ID,2020 GEOID
count,299694.000000,299705.000000,299679.000000,298915.000000,2.997050e+05,2.996940e+05
mean,98176.001962,2022.344666,36.663313,28.754589,2.509924e+08,5.296742e+10
std,2652.053836,3.093007,76.034423,14.892388,6.238702e+07,1.687605e+09
min,1030.000000,1999.000000,0.000000,1.000000,4.469000e+03,1.001020e+09
25%,98052.000000,2021.000000,0.000000,17.000000,2.283017e+08,5.303301e+10
50%,98134.000000,2023.000000,0.000000,32.000000,2.679271e+08,5.303303e+10
75%,98391.000000,2024.000000,32.000000,42.000000,2.845359e+08,5.305394e+10
max,99801.000000,2027.000000,337.000000,49.000000,4.791150e+08,6.601095e+10

In [8]:
df.duplicated().sum()

df.isnull().mean()

VIN (1-10)                                           0.000000
County                                               0.000037
City                                                 0.000037
State                                                0.000000
Postal Code                                          0.000037
Model Year                                           0.000000
Make                                                 0.000000
Model                                                0.000000
Electric Vehicle Type                                0.000000
Clean Alternative Fuel Vehicle (CAFV) Eligibility    0.000000
Electric Range                                       0.000087
Legislative District                                 0.002636
DOL Vehicle ID                                       0.000000
Vehicle Location                                     0.000067
Electric Utility                                     0.000037
2020 GEOID                                           0.000037
dtype: float64